# Generated by Django 5.2.8 on 2025-11-22 18:25

import ckeditor.fields
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Leader',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rank', models.CharField(max_length=50, verbose_name='Звание')),
                ('full_name', models.CharField(max_length=100, verbose_name='ФИО')),
                ('position', models.CharField(choices=[('chief', 'Начальник Пограничного управления'), ('deputy_chief', 'Первый заместитель — начальник штаба'), ('deputy_personnel', 'Заместитель по работе с личным составом'), ('deputy_coast', 'Заместитель — начальник отдела береговой охраны'), ('deputy_logistics', 'Заместитель по тылу'), ('other', 'Иное руководство')], max_length=50, verbose_name='Должность')),
                ('photo', models.ImageField(upload_to='leaders/', verbose_name='Фотография')),
                ('years_service', models.CharField(blank=True, max_length=100, verbose_name='Годы службы')),
                ('awards', ckeditor.fields.RichTextField(blank=True, verbose_name='Награды и заслуги')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок сортировки')),
            ],
            options={
                'verbose_name': 'Руководитель',
                'verbose_name_plural': 'Руководство',
                'ordering': ['sort_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='News',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('slug', models.SlugField(max_length=200, unique_for_date='pub_date', verbose_name='URL (авто)')),
                ('content', ckeditor.fields.RichTextField(verbose_name='Текст новости')),
                ('pub_date', models.DateField(default=django.utils.timezone.now, verbose_name='Дата публикации')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('is_important', models.BooleanField(default=False, verbose_name='Важное объявление (на главную)')),
                ('image', models.ImageField(blank=True, null=True, upload_to='news/', verbose_name='Фото (необязательно)')),
            ],
            options={
                'verbose_name': 'Новость',
                'verbose_name_plural': 'Новости и пресс-релизы',
                'ordering': ['-pub_date'],
            },
        ),
    ]
