# Generated by Django 5.2.8 on 2025-11-24 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Должность')),
                ('rank', models.CharField(blank=True, max_length=100, verbose_name='Звание')),
                ('salary_from', models.PositiveIntegerField(verbose_name='Денежное довольствие от, руб.')),
                ('salary_to', models.PositiveIntegerField(blank=True, null=True, verbose_name='Денежное довольствие до, руб.')),
                ('requirements', models.TextField(verbose_name='Требования')),
                ('duties', models.TextField(blank=True, verbose_name='Обязанности')),
                ('benefits', models.TextField(blank=True, verbose_name='Льготы и гарантии')),
                ('is_published', models.BooleanField(default=True, verbose_name='Опубликовано')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
            ],
            options={
                'verbose_name': 'Вакансия (контракт)',
                'verbose_name_plural': 'Вакансии на контракт',
                'ordering': ['sort_order'],
            },
        ),
    ]
