# Generated by Django 5.2.8 on 2025-11-24 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_vacancy'),
    ]

    operations = [
        migrations.AddField(
            model_name='vacancy',
            name='contact_phone',
            field=models.CharField(blank=True, max_length=30, verbose_name='Телефон для связи по вакансии'),
        ),
        migrations.AddField(
            model_name='vacancy',
            name='military_unit',
            field=models.CharField(blank=True, max_length=200, verbose_name='Районное подразделение'),
        ),
    ]
